SELECT QryYearlyMonthly_PRT_DetailCal.ShipName_En, QryYearlyMonthly_PRT_DetailCal.ShipID,
QryYearlyMonthly_PRT_DetailCal.CP_Year, QryYearlyMonthly_PRT_DetailCal.CP_Month,
QryYearlyMonthly_PRT_DetailCal.OperationMethod, QryYearlyMonthly_PRT_DetailCal.PlanProfit,
QryYearlyMonthly_PRT_DetailCal.PROFIT AS YearlyMonthProfit, QryYearlyMonthly_PRT_DetailCal.PlanIncome,
QryYearlyMonthly_PRT_DetailCal.ACTL_FRT AS YearlyMonthIncome, QryYearlyMonthly_PRT_DetailCal.PlanExpense,
QryYearlyMonthly_PRT_DetailCal.Exp AS YearlyMonthExpense, QryYearlyMonthly_PRT_DetailCal.PD_L AS YearlyMonthPD_L,
QryYearlyMonthly_PRT_DetailCal.PD_D AS YearlyMonthPD_D, QryYearlyMonthly_PRT_DetailCal.FO AS YearlyMonthFO,
QryYearlyMonthly_PRT_DetailCal.DO AS YearlyMonthDO, QryYearlyMonthly_PRT_DetailCal.LO AS YearlyMonthLO,
QryYearlyMonthly_PRT_DetailCal.SS AS YearlyMonthSS, QryYearlyMonthly_PRT_DetailCal.CTM AS YearlyMonthCTM,
QryYearlyMonthly_PRT_DetailCal.OTHERS AS YearlyMonthOTHERS
FROM QryYearlyMonthly_PRT_DetailCal;

#QryYearlyMonthly_PRT_DetailCal
SELECT QryYearlyMonthly_AcDetail_Cal.ShipName_En, QryYearlyMonthly_AcDetail_Cal.RegNo AS ShipID,
QryYearlyMonthly_AcDetail_Cal.CP_Year, QryYearlyMonthly_AcDetail_Cal.CP_Month,
QryYearlyMonthly_AcDetail_Cal.OperationMethod,
Tbl_Yearly_Quarter_MonthPlan.Income AS PlanIncome, Tbl_Yearly_Quarter_MonthPlan.Expense AS PlanExpense,
Tbl_Yearly_Quarter_MonthPlan.Profit AS PlanProfit,
IfNull(QryYearlyMonthly_AcDetail_Cal.FRT,0) AS FRT,
IfNull(QryYearlyMonthly_AcDetail_Cal.DMRG,0) AS DMRG,
IfNull(QryYearlyMonthly_AcDetail_Cal.D_FRT,0) AS DEAD_FRT,
IfNull(QryYearlyMonthly_AcDetail_Cal.ADD IN,0) AS ADD_IN,
IfNull(QryYearlyMonthly_AcDetail_Cal.BRKG,0) AS BRKG,
FRT+DMRG+DEAD_FRT+ADD_IN AS ACTL_FRT,
BRKG+PDA+FO+DO+LO+SS+FW+REPAIR+CTM+PRM+REG_OWNER+ISM+SURVEY+TELCOM+SHIP_CERT+CREW_CERT+PLT+FMA+OTHER AS EXP,
ACTL_FRT-EXP AS PROFIT, PD_L+PD_D AS PDA,
IfNull(QryYearlyMonthly_AcDetail_Cal.PDA_L,0) AS PDA_L,
IfNull(QryYearlyMonthly_AcDetail_Cal.PDA_D,0) AS PDA_D,
IfNull(QryYearlyMonthly_AcDetail_Cal.TG_L,0) AS TG_L,
IfNull(QryYearlyMonthly_AcDetail_Cal.TG_D,0) AS TG_D,
IfNull(QryYearlyMonthly_AcDetail_Cal.LKT_L,0) AS LKT_L,
IfNull(QryYearlyMonthly_AcDetail_Cal.LKT_D,0) AS LKT_D,
PDA_L+TG_L+LKT_L AS PD_L, PDA_D+TG_D+LKT_D AS PD_D,
IfNull(QryYearlyMonthly_AcDetail_Cal.FO,0) AS FO,
IfNull(QryYearlyMonthly_AcDetail_Cal.DO,0) AS DO,
IfNull(QryYearlyMonthly_AcDetail_Cal.LO,0) AS LO,
IfNull(QryYearlyMonthly_AcDetail_Cal.SS,0) AS SS,
IfNull(QryYearlyMonthly_AcDetail_Cal.FW,0) AS FW,
IfNull(QryYearlyMonthly_AcDetail_Cal.REPAIR,0) AS REPAIR,
IfNull(QryYearlyMonthly_AcDetail_Cal.CTM,0) AS CTM,
IfNull(QryYearlyMonthly_AcDetail_Cal.PRM,0) AS PRM,
IfNull(QryYearlyMonthly_AcDetail_Cal.REG OWNER,0) AS REG_OWNER,
IfNull(QryYearlyMonthly_AcDetail_Cal.ISM,0) AS ISM,
IfNull(QryYearlyMonthly_AcDetail_Cal.SURVEY,0) AS SURVEY,
IfNull(QryYearlyMonthly_AcDetail_Cal.SHIP CERT,0) AS SHIP_CERT,
IfNull(QryYearlyMonthly_AcDetail_Cal.CREW CERT,0) AS CREW_CERT,
IfNull(QryYearlyMonthly_AcDetail_Cal.TELCOM,0) AS TELCOM,
IfNull(QryYearlyMonthly_AcDetail_Cal.PLT,0) AS PLT,
IfNull(QryYearlyMonthly_AcDetail_Cal.FMA,0) AS FMA,
IfNull(QryYearlyMonthly_AcDetail_Cal.OTHER,0) AS OTHER,
EXP-PDA-FO-DO-LO-SS-CTM AS OTHERS
FROM (ClassRegistry INNER JOIN (QryYearlyMonthly_AcDetail_Cal INNER JOIN Tbl_Yearly_Quarter_MonthPlan ON (QryYearlyMonthly_AcDetail_Cal.RegNo=Tbl_Yearly_Quarter_MonthPlan.ShipID) AND (QryYearlyMonthly_AcDetail_Cal.CP_Year=Tbl_Yearly_Quarter_MonthPlan.Yearly) AND (QryYearlyMonthly_AcDetail_Cal.CP_Month=Tbl_Yearly_Quarter_MonthPlan.Month)) ON ClassRegistry.RegNo=Tbl_Yearly_Quarter_MonthPlan.ShipID) INNER JOIN Tbl_KS_Ships ON ClassRegistry.RegNo=Tbl_KS_Ships.ShipID
ORDER BY QryYearlyMonthly_AcDetail_Cal.CP_Year, QryYearlyMonthly_AcDetail_Cal.CP_Month;

#QryYearlyMonthly_AcDetail_Cal
SELECT
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'FRT' then Tbl_INVOICE.Amount else 0 end) as FRT,
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'DMRG' then Tbl_INVOICE.Amount else 0 end) as DMRG,
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'D_FRT' then Tbl_INVOICE.Amount else 0 end) as D_FRT,
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'ADD IN' then Tbl_INVOICE.Amount else 0 end) as ADD_IN,
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'BRKG' then Tbl_INVOICE.Amount else 0 end) as BRKG,
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'PDA_L' then Tbl_INVOICE.Amount else 0 end) as PDA_L,
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'PDA_D' then Tbl_INVOICE.Amount else 0 end) as PDA_D,
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'TG_L' then Tbl_INVOICE.Amount else 0 end) as TG_L,
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'TG_D' then Tbl_INVOICE.Amount else 0 end) as TG_D,
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'LKT_L' then Tbl_INVOICE.Amount else 0 end) as LKT_L,
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'LKT_D' then Tbl_INVOICE.Amount else 0 end) as LKT_D,
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'FO' then Tbl_INVOICE.Amount else 0 end) as FO,
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'DO' then Tbl_INVOICE.Amount else 0 end) as DO,
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'LO' then Tbl_INVOICE.Amount else 0 end) as LO,
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'SS' then Tbl_INVOICE.Amount else 0 end) as SS,
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'FW' then Tbl_INVOICE.Amount else 0 end) as FW,
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'REPAIR' then Tbl_INVOICE.Amount else 0 end) as REPAIR,
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'CTM' then Tbl_INVOICE.Amount else 0 end) as CTM,
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'PRM' then Tbl_INVOICE.Amount else 0 end) as PRM,
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'REG OWNER' then Tbl_INVOICE.Amount else 0 end) as REG_OWNER,
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'ISM' then Tbl_INVOICE.Amount else 0 end) as ISM,
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'SURVEY' then Tbl_INVOICE.Amount else 0 end) as SURVEY,
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'TELCOM' then Tbl_INVOICE.Amount else 0 end) as TELCOM,
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'SHIP CERT' then Tbl_INVOICE.Amount else 0 end) as SHIP_CERT,
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'CREW CERT' then Tbl_INVOICE.Amount else 0 end) as CREW_CERT,
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'PLT' then Tbl_INVOICE.Amount else 0 end) as PLT,
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'FMA' then Tbl_INVOICE.Amount else 0 end) as FMA,
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'OTHER' then Tbl_INVOICE.Amount else 0 end) as OTHER,
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'ADMNSTN' then Tbl_INVOICE.Amount else 0 end) as ADMNSTN,
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'TRAVEL' then Tbl_INVOICE.Amount else 0 end) as TRAVEL,
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'RICE' then Tbl_INVOICE.Amount else 0 end) as RICE,
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'DEPOSIT' then Tbl_INVOICE.Amount else 0 end) as DEPOSIT,
sum(case Tbl_AC_Deatil_item.AC_Detail_Item_Abb when 'RMT' then Tbl_INVOICE.Amount else 0 end) as RMT,
ClassRegistry.ShipName_En, ClassRegistry.RegNo, Year(Appl_Date) AS CP_Year, Month(Appl_Date) AS CP_Month, Tbl_KS_Ships.ID, Tbl_KS_Ships.OperationMethod
FROM Tbl_AC_Deatil_item INNER JOIN ((ClassRegistry INNER JOIN Tbl_INVOICE ON ClassRegistry.RegNo=Tbl_INVOICE.ShipID) INNER JOIN Tbl_KS_Ships ON ClassRegistry.RegNo=Tbl_KS_Ships.ShipID) ON Tbl_AC_Deatil_item.ID=Tbl_INVOICE.AC_Items
WHERE (((Year(Appl_Date)) Is Not Null) AND ((Tbl_INVOICE.Curency)='USD') AND ((Tbl_INVOICE.Completion)=1) AND ((Tbl_INVOICE.Object)='Business'))
GROUP BY ClassRegistry.ShipName_En, ClassRegistry.RegNo, Year(Appl_Date), Month(Appl_Date), Tbl_KS_Ships.ID, Tbl_KS_Ships.OperationMethod
ORDER BY Year(Appl_Date), Month(Appl_Date), Tbl_KS_Ships.ID

